import React, { useState, useEffect } from 'react';
import { Sun, Moon, Upload, User, History, FileText, Download } from 'lucide-react';
import axios from 'axios';
import { jsPDF } from "jspdf";
import "jspdf-autotable";
import {
  Chart as ChartJS,
  CategoryScale,
  LinearScale,
  BarElement,
  PointElement,
  LineElement,
  Title,
  Tooltip,
  Legend,
} from 'chart.js';
import { Bar, Line } from 'react-chartjs-2';
ChartJS.register(
  CategoryScale, LinearScale, BarElement, 
  PointElement, LineElement, Title, Tooltip, Legend
);

export default function Dashboard({ onLogout }) {
  const [darkMode, setDarkMode] = useState(false);
  const [username, setUsername] = useState("User");
  const [stats, setStats] = useState(null);
  const [history, setHistory] = useState([]); // Stores last 5 uploads
  const chartData = {
    labels: ['Avg Temperature', 'Avg Pressure'],
    datasets: [
      {
        label: 'Parameters',
        data: stats ? [stats.avg_temp, stats.avg_pressure] : [0, 0],
        backgroundColor: ['rgba(147, 51, 234, 0.6)', 'rgba(59, 130, 246, 0.6)'],
        borderRadius: 10,
      },
    ],
  };

  useEffect(() => {
    const storedUser = localStorage.getItem('username');
    if (storedUser) setUsername(storedUser);
    fetchHistory(); // Load history when page opens
  }, []);

  const fetchHistory = async () => {
    try {
      const token = localStorage.getItem('token');
      const response = await axios.get('https://visualizer-o864.onrender.com/api/history/', {
        headers: { 'Authorization': `Bearer ${token}` }
      });
      setHistory(response.data);
    } catch (error) {
      console.error("Could not fetch history");
    }
  };
  const downloadPDF = () => {
  const doc = new jsPDF();
  
  // 1. Add Header
  doc.setFontSize(20);
  doc.setTextColor(79, 70, 229); // Purple color
  doc.text("ChemVisualizer Analysis Report", 14, 22);
  
  // 2. Add User Info
  doc.setFontSize(12);
  doc.setTextColor(100);
  doc.text(`Generated by: ${username}`, 14, 32);
  doc.text(`Date: ${new Date().toLocaleDateString()}`, 14, 38);

  // 3. Add Analysis Table
  if (stats) {
    doc.autoTable({
      startY: 50,
      head: [['Parameter', 'Value']],
      body: [
        ['Total Equipment Items', stats.total_count],
        ['Average Temperature', `${stats.avg_temp}°C`],
        ['Average Pressure', `${stats.avg_pressure} PSI`],
      ],
      theme: 'grid',
      headStyles: { fillColor: [124, 58, 237] } // Match your purple UI
    });
  } else {
    doc.text("No data available for report generation.", 14, 50);
  }

  // 4. Save the file
  doc.save(`${username}_Chemical_Report.pdf`);
};
const handleLogout = () => {
  // 1. Remove the token and username from storage
  localStorage.removeItem('token');
  localStorage.removeItem('username');
  
  // 2. Call the logout function passed from App.js
  onLogout(); 
  
  alert("You have been logged out safely.");
};

  const handleFileUpload = async (event) => {
    const file = event.target.files[0];
    if (!file) return;

    const formData = new FormData();
    formData.append('file', file);

    try {
      const token = localStorage.getItem('token');
const response = await axios.post('https://visualizer-o864.onrender.com/api/upload/', formData, {
    headers: {
        'Authorization': `Bearer ${token}` // This identifies the user for their private silo
    }
});
      setStats(response.data);
      fetchHistory(); // Refresh history list
    } catch (error) {
      alert("Upload failed.");
    }
  };

  return (
    <div className={darkMode ? "dark bg-gray-900 text-white min-h-screen" : "bg-gray-50 text-gray-800 min-h-screen"}>
      {/* NAVBAR */}
      <nav className="flex justify-between items-center p-6 bg-white dark:bg-gray-800 shadow-md">
        <h2 className="text-2xl font-bold bg-gradient-to-r from-purple-600 to-indigo-600 bg-clip-text text-transparent">ChemVisualizer</h2>
        <div className="flex items-center gap-6">
          <button onClick={() => setDarkMode(!darkMode)} className="p-2 rounded-full hover:bg-gray-100 dark:hover:bg-gray-700">
            {darkMode ? <Sun size={24} className="text-yellow-400" /> : <Moon size={24} />}
          </button>
          <div className="flex items-center gap-2 font-semibold px-4 py-2 bg-purple-50 dark:bg-gray-700 rounded-full">
            <User size={18} className="text-purple-600" />
            <span>{username}</span>
          </div>
        </div>
        <div className="flex items-center space-x-4">
  <div className="flex items-center bg-purple-100 px-4 py-2 rounded-full">
    <User size={18} className="text-purple-600 mr-2" />
    <span className="text-purple-700 font-bold lowercase">
      {localStorage.getItem('username')}
    </span>
  </div>
  
  <button 
    onClick={handleLogout}
    className="bg-red-500 hover:bg-red-600 text-white px-4 py-2 rounded-xl text-sm font-bold transition-colors shadow-lg shadow-red-200"
  >
    LOGOUT
  </button>
</div>
      </nav>

      <div className="p-8 max-w-7xl mx-auto grid grid-cols-1 md:grid-cols-4 gap-8">
        
        {/* LEFT: HISTORY PART */}
        <div className="md:col-span-1 space-y-4">
          <h3 className="flex items-center gap-2 font-bold text-lg"><History size={20}/> Last 5 Uploads</h3>
          <div className="space-y-3">
            {history.length > 0 ? history.map((item, index) => (
              <div key={index} className="p-4 bg-white dark:bg-gray-800 rounded-2xl shadow-sm hover:border-purple-500 border-2 border-transparent cursor-pointer transition-all">
                <p className="text-sm font-bold truncate">{item.filename}</p>
                <p className="text-xs text-gray-400">{new Date(item.upload_date).toLocaleDateString()}</p>
              </div>
            )) : <p className="text-gray-400 text-sm">No history yet</p>}
          </div>
        </div>

        {/* RIGHT: ANALYZED DATA PART */}
        <div className="md:col-span-3 space-y-6">
          <div className="bg-gradient-to-r from-purple-600 to-indigo-600 p-8 rounded-[30px] text-white flex justify-between items-center shadow-xl">
            <div>
              <h1 className="text-3xl font-bold text-white">Analyzed Data</h1>
              <p className="opacity-80">Overview of your chemical equipment parameters</p>
            </div>
            <label className="bg-white text-purple-600 px-6 py-3 rounded-full font-bold cursor-pointer flex items-center gap-2">
              <Upload size={20} /> Upload New CSV
              <input type="file" className="hidden" onChange={handleFileUpload} accept=".csv" />
            </label>
          </div>

          {/* LEFT: HISTORY SIDEBAR */}
<div className="md:col-span-1 space-y-4">
  <h3 className="flex items-center gap-2 font-bold text-lg">
    <History size={20}/> Last 5 Uploads
  </h3>
  <div className="space-y-3">
    {history.length > 0 ? (
      history.map((item, index) => (
        <div 
          key={index} 
          className="p-4 bg-white dark:bg-gray-800 rounded-2xl shadow-sm border-2 border-transparent hover:border-purple-500 cursor-pointer transition-all"
        >
          <div className="flex items-center gap-3">
            <FileText className="text-purple-600" size={18} />
            <div className="truncate">
              <p className="text-sm font-bold truncate">{item.filename}</p>
              <p className="text-xs text-gray-400">
                {new Date(item.upload_date).toLocaleDateString()}
              </p>
            </div>
          </div>
        </div>
      ))
    ) : (
      <div className="p-4 bg-gray-100 dark:bg-gray-800 rounded-2xl border-dashed border-2 border-gray-300 dark:border-gray-600 text-center">
        <p className="text-gray-400 text-sm">No uploads yet</p>
      </div>
    )}
  </div>
</div>

          {/* STATS CARDS */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            <div className="bg-white dark:bg-gray-800 p-6 rounded-[25px] shadow-sm border border-gray-100 dark:border-gray-700">
              <p className="text-gray-400 text-sm mb-1">Total Count</p>
              <h2 className="text-3xl font-bold">{stats ? stats.total_count : "0"}</h2>
            </div>
            <div className="bg-white dark:bg-gray-800 p-6 rounded-[25px] shadow-sm border border-gray-100 dark:border-gray-700">
              <p className="text-gray-400 text-sm mb-1">Avg Temperature</p>
              <h2 className="text-3xl font-bold text-orange-500">{stats ? `${stats.avg_temp}°C` : "--"}</h2>
            </div>
            <div className="bg-white dark:bg-gray-800 p-6 rounded-[25px] shadow-sm border border-gray-100 dark:border-gray-700">
              <p className="text-gray-400 text-sm mb-1 text-blue-500">Avg Pressure</p>
              <h2 className="text-3xl font-bold text-blue-500">{stats ? `${stats.avg_pressure} PSI` : "--"}</h2>
            </div>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-8 mt-10">
      {/* BAR CHART */}
      <div className="bg-white dark:bg-gray-800 p-6 rounded-[30px] shadow-sm">
        <h3 className="font-bold mb-4">Equipment Parameter Comparison</h3>
        <Bar data={chartData} options={{ responsive: true }} />
      </div>

      {/* LINE CHART */}
      <div className="bg-white dark:bg-gray-800 p-6 rounded-[30px] shadow-sm">
        <h3 className="font-bold mb-4">Trend Visualization</h3>
        <Line 
          data={chartData} 
          options={{ responsive: true, plugins: { legend: { display: false } } }} 
        />
      </div>

      {/* Add this below your Charts section in Dashboard.js */}
<div className="mt-10 bg-white dark:bg-gray-800 rounded-[30px] shadow-sm overflow-hidden">
  <div className="p-6 border-b border-gray-100 dark:border-gray-700 flex justify-between items-center">
    <h3 className="font-bold text-lg">Detailed Equipment Log</h3>
    <span className="text-sm text-gray-400">{stats?.rows?.length || 0} Entries</span>
  </div>
  <div className="overflow-x-auto max-h-96">
    <table className="w-full text-left border-collapse">
      <thead className="bg-gray-50 dark:bg-gray-900 sticky top-0">
        <tr>
          {stats?.rows?.[0] && Object.keys(stats.rows[0]).map(key => (
            <th key={key} className="p-4 text-xs font-bold uppercase text-gray-400 border-b border-gray-100 dark:border-gray-700">
              {key}
            </th>
          ))}
        </tr>
      </thead>
      <tbody>
        {stats?.rows?.map((row, i) => (
          <tr key={i} className="hover:bg-purple-50 dark:hover:bg-gray-700 transition-colors">
            {Object.values(row).map((val, j) => (
              <td key={j} className="p-4 text-sm border-b border-gray-100 dark:border-gray-700">
                {val}
              </td>
            ))}
          </tr>
        ))}
      </tbody>
    </table>
  </div>
</div>
    </div>

          {/* DOWNLOAD PART */}
          <div className="flex justify-end">
            <button 
  onClick={downloadPDF}
  className="flex items-center gap-2 bg-gray-800 text-white px-6 py-3 rounded-xl font-bold hover:bg-black transition-colors"
>
  <Download size={20} /> Download Report (PDF)
</button>
          </div>
        </div>
      </div>
    </div>
  );
}